zadania z zajec nr 3
dabrowskia/ADP2020 pull request #32
Opened 2020-05-09 07:10 UTC by korneliacwik

2020-05-16 09:28 UTC, dabrowskia requested changes
usuń proszę pliki z folderu data z commit-owanych plików. Nie wysyłamy zazwyczaj takich dużych plików na repozytorium w chmurze.

2020-05-16 09:28 UTC, dabrowskia commented on personal/korneliacwik/reports/rataje.Rmd
> +linearModel2 <- train(data = wtorne.rataje.df,
Dbaj o czytelność kodu poprzez dodawanie spacji wokół znaków (jak np. "+")

2020-05-16 09:28 UTC, dabrowskia commented on personal/korneliacwik/reports/zajecia3.Rmd
> +lnd_point = st_point(c(16.56, 52.24))           #poznań
Do przypisywania zmiennych używamy <- . Jest to dobra praktyka czytelności kodu. "=" też zadziała, ale nie jest zazwyczaj uznawana za przejaw czytelnego kodu.  "=" jest wykorzystywane do argumentów wewnątrz funkcji więc warto to rozrózniać.

2020-05-17 11:29 UTC, korneliacwik commented
> usuń proszę pliki z folderu data z commit-owanych plików. Nie wysyłamy zazwyczaj takich dużych plików na repozytorium w chmurze.

@dabrowskia Usunęłam pliki.

2020-05-21 16:01 UTC, merged