zajecia-3
dabrowskia/ADP2020 pull request #33
Opened 2020-05-09 07:10 UTC by wojciechowskadominika

2020-05-16 09:18 UTC, dabrowskia requested changes
Usuń proszę z repozytorium pliki data (powiaty, województwa, etc.) Zajmują bardzo dużo miejsca, i nie trzyma się ich na repozytorium.

2020-05-16 09:18 UTC, dabrowskia commented on personal/dominikawojciechowska/reports/Zajecia3.Rmd
> +## Zadanie 0 - punkt w Posce na mapie świata
literówka w "Polsce". To drobiazg, ale takie drobiazgi sprawiają na końcowy odbiór raportu przez pracodawcę. Zalecam przejrzenie raportu pod kątem rzucających się w oczy literówek.

2020-05-30 13:06 UTC, wojciechowskadominika commented
Usunęłam z repozytorium pliki powiaty, województwa, etc. oraz usunęłam literówkę.

2020-06-01 11:33 UTC, dabrowskia requested changes
Usuń prosze wszystkie pliki shapefile (prj, shp, dbf...) oraz zmień ścieżkę dostępu na względną.

2020-06-01 11:33 UTC, dabrowskia commented on personal/dominikawojciechowska/reports/Zajecia3.Rmd
> +powiaty <- st_read( dsn = 'j:/Desktop/jednostki_organizacyjne/Powiaty.shp')
poproszę ścieżkę względną :) .

2020-06-15 16:24 UTC, wojciechowskadominika commented
Usunęłam wszystkie pliki shapefile (prj, shp, dbf...) oraz zmieniłam ścieżkę dostępu na względną.

2020-06-20 12:38 UTC, dabrowskia approved these changes

2020-06-20 12:38 UTC, merged

2020-06-20 19:07 UTC, wojciechowskadominika commented
Dzień dobry,

Proszę o sprawdzenie czy w moim przypadku zajęcia 4 również zostały zaliczone?

Dziękuję.

Pozdrawiam,
Dominika Wojciechowska


Pobierz aplikację Outlook dla systemu iOS<https://aka.ms/o0ukef>
________________________________
Od: dabrowskia <notifications@github.com>
Wysłane: Saturday, June 20, 2020 2:39:07 PM
Do: dabrowskia/ADP2020 <ADP2020@noreply.github.com>
DW: Dominika Wojciechowska <domwoj1@st.amu.edu.pl>; Author <author@noreply.github.com>
Temat: Re: [dabrowskia/ADP2020] zajecia-3 (#33)


Merged #33<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdabrowskia%2FADP2020%2Fpull%2F33&data=01%7C01%7Cdomwoj1%40st.amu.edu.pl%7C1263378bb34b4a574edc08d81516edb2%7C73689ee1b42f4e25a5f666d1f29bc092%7C0&sdata=fbZqB%2FPEzvvCPFj8CjL0%2F6V4HufYkxxmYhjaf6FraJg%3D&reserved=0> into master.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdabrowskia%2FADP2020%2Fpull%2F33%23event-3464657730&data=01%7C01%7Cdomwoj1%40st.amu.edu.pl%7C1263378bb34b4a574edc08d81516edb2%7C73689ee1b42f4e25a5f666d1f29bc092%7C0&sdata=ZNp1JPzsxOO58u8Yb3rln7UVTF0wH6xWDBTMweawTZ4%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPBXJ6ZAM3S7AXZBAA2FHBLRXSUWXANCNFSM4M4VYM5A&data=01%7C01%7Cdomwoj1%40st.amu.edu.pl%7C1263378bb34b4a574edc08d81516edb2%7C73689ee1b42f4e25a5f666d1f29bc092%7C0&sdata=0R%2BOiBHkXvx8rRf30wschjbfErjoON3FSd5ALqH2FcI%3D&reserved=0>.

2020-06-20 19:21 UTC, dabrowskia commented
Są zaliczone. Wszystko w porządku.

2020-06-20 19:23 UTC, wojciechowskadominika commented
Super, dziękuję.

Pobierz aplikację Outlook dla systemu iOS<https://aka.ms/o0ukef>
________________________________
Od: dabrowskia <notifications@github.com>
Wysłane: Saturday, June 20, 2020 9:21:59 PM
Do: dabrowskia/ADP2020 <ADP2020@noreply.github.com>
DW: Dominika Wojciechowska <domwoj1@st.amu.edu.pl>; Author <author@noreply.github.com>
Temat: Re: [dabrowskia/ADP2020] zajecia-3 (#33)


Są zaliczone. Wszystko w porządku.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdabrowskia%2FADP2020%2Fpull%2F33%23issuecomment-647035865&data=01%7C01%7Cdomwoj1%40st.amu.edu.pl%7Ce01e3c4ad6284e08abaf08d8154f34e3%7C73689ee1b42f4e25a5f666d1f29bc092%7C0&sdata=rPHohNWVqY6SEQtMGjkJ57HG4Q%2FUtk5IC0lWIEFZcuo%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPBXJ66Z22BTFGEMUDUON5DRXUD5PANCNFSM4M4VYM5A&data=01%7C01%7Cdomwoj1%40st.amu.edu.pl%7Ce01e3c4ad6284e08abaf08d8154f34e3%7C73689ee1b42f4e25a5f666d1f29bc092%7C0&sdata=hxuFLTdzkwhKYsrXhz%2BoWug7cDY9U2KIm89Od2fJsds%3D&reserved=0>.